## **Lab1-02** ##

In [1]:
import numpy as np

In [4]:
A = np.array([[1.32, 3.25, 2.77],
                   [-3.57, 2.12, -3.26],
                   [-9.87, 3.33, 2.15]])

#### Calcular la inversa de la matriz A empleando inv de linal y multiplicar A por su inversa ####

In [5]:
invA = np.linalg.inv(A)
invA

array([[ 0.08813184,  0.01278826, -0.09415603],
       [ 0.22786099,  0.17254888, -0.03193749],
       [ 0.05166706, -0.20854309,  0.08234036]])

In [ ]:
product = np.matmul(invA, A)
product

array([[ 1.00000000e+00,  4.72944060e-17,  4.93022098e-17],
       [-2.30193534e-17,  1.00000000e+00,  1.92962312e-16],
       [ 6.79652033e-17, -1.27456013e-17,  1.00000000e+00]])

### Hacer lo mismo con 5 matrices distintas ###

In [13]:
def multiply_matrices_A_and_invA(A):
    invA = np.linalg.inv(A)
    product = np.matmul(invA, A)
    return product

matrices =[
        np.array([[1.32, 3.25, 2.77],
                   [-3.57, 2.12, -3.26],
                   [-9.87, 3.33, 2.15]]),
        np.array([[1.32, 3.25, 2.77],
                   [-3.57, 2.12, -3.26],
                   [-9.87, 3.33, 2.15]]),
        np.array([[1.32, 3.25, 2.77],
                   [-3.57, 2.12, -3.26],
                   [-9.87, 3.33, 2.15]]),
        np.array([[1.32, 3.25, 2.77],
                   [-3.57, 2.12, -3.26],
                   [-9.87, 3.33, 2.15]]),
        np.array([[1.32, 3.25, 2.77],
                   [-3.57, 2.12, -3.26],
                   [-9.87, 3.33, 2.15]]),
    ]

for i, matrix in enumerate(matrices):
    print(f"Matrix {i+1}")
    print(multiply_matrices_A_and_invA(matrix))
    print("--------------------------------")

Matrix 1
[[ 1.00000000e+00  4.72944060e-17  4.93022098e-17]
 [-2.30193534e-17  1.00000000e+00  1.92962312e-16]
 [ 6.79652033e-17 -1.27456013e-17  1.00000000e+00]]
--------------------------------
Matrix 2
[[ 1.00000000e+00  4.72944060e-17  4.93022098e-17]
 [-2.30193534e-17  1.00000000e+00  1.92962312e-16]
 [ 6.79652033e-17 -1.27456013e-17  1.00000000e+00]]
--------------------------------
Matrix 3
[[ 1.00000000e+00  4.72944060e-17  4.93022098e-17]
 [-2.30193534e-17  1.00000000e+00  1.92962312e-16]
 [ 6.79652033e-17 -1.27456013e-17  1.00000000e+00]]
--------------------------------
Matrix 4
[[ 1.00000000e+00  4.72944060e-17  4.93022098e-17]
 [-2.30193534e-17  1.00000000e+00  1.92962312e-16]
 [ 6.79652033e-17 -1.27456013e-17  1.00000000e+00]]
--------------------------------
Matrix 5
[[ 1.00000000e+00  4.72944060e-17  4.93022098e-17]
 [-2.30193534e-17  1.00000000e+00  1.92962312e-16]
 [ 6.79652033e-17 -1.27456013e-17  1.00000000e+00]]
--------------------------------
