Factorizacion LU

In [1]:
import numpy as np

In [72]:
def lu_factorization(A):
    A = np.array(A, dtype=float)
    n = len(A)
    L = np.eye(n)
    U = A.copy()

    # Creando la triangular superior
    for i in range(n):
        if U[i][i] == 0:
            return "No se puede factorizar"
        
        # Eliminando la columna debajo de la diagonal
        for j in range(i + 1, n):
            multiplier = U[j][i] / U[i][i]
            L[j][i] = multiplier 
            U[j][i:] -= multiplier * U[i][i:]
    return L, U

In [73]:
A = [
        [0, 2, 1],
        [1, -2, -3],
        [3, -1, 1]
    ]

r = lu_factorization(A)
print(r)

No se puede factorizar


In [74]:
A = [
        [2, 2, 1],
        [1, -2, -3],
        [3, -1, 1]
    ]

l,u = lu_factorization(A)
print("L:")
print(l)
print("--------------------------------")
print("U:")
print(u)

L:
[[1.         0.         0.        ]
 [0.5        1.         0.        ]
 [1.5        1.33333333 1.        ]]
--------------------------------
U:
[[ 2.          2.          1.        ]
 [ 0.         -3.         -3.5       ]
 [ 0.          0.          4.16666667]]


In [75]:
A = [
        [3, 1, 2],
        [6, 3, 4],
        [3, 1, 5]
    ]

l,u = lu_factorization(A)
print("L:")
print(l)
print("--------------------------------")
print("U:")
print(u)

L:
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
--------------------------------
U:
[[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]
