
1.  Implemente la factorización LDLt
    - El programa debe recibir como entrada la matriz A.
    - La salida deben ser la matrices  L y  D   o un mensaje de que la factorización  no es posible.
    - Compruebe el funcionamiento del programa empleando una matriz definida positiva.

2.  Implemente la factorización LLt (Factorización de Cholesky)
    - El programa debe recibir como entrada la matriz A.
    - La salida deben ser la matriz L  o un mensaje de que la factorización  no es posible.
    - Compruebe el funcionamiento del programa empleando una matriz definida positiva.


In [7]:
import numpy as np

In [8]:
def ldlt_factorization(A):
    """
    Factorización LDLt: A = L * D * L^T
    
    Entrada: Matriz A (numpy array)
    Salida: (L, D) si es posible, None si no es posible
    """
    A = np.array(A, dtype=float)
    n = A.shape[0]
    
    L = np.eye(n)
    D = np.zeros(n)
    
    for i in range(n):
        sum_val = 0.0
        for k in range(i):
            sum_val += L[i, k]**2 * D[k]
        
        D[i] = A[i, i] - sum_val
        
        if D[i] <= 1e-10:
            print("La factorización no es posible: la matriz no es definida positiva")
            return None
        
        for j in range(i + 1, n):
            sum_val = 0.0
            for k in range(i):
                sum_val += L[j, k] * L[i, k] * D[k]
            
            L[j, i] = (A[j, i] - sum_val) / D[i]
    
    D_matrix = np.diag(D)
    
    return L, D_matrix

In [9]:
def cholesky_factorization(A):
    """
    Factorización de Cholesky: A = L * L^T
    
    Entrada: Matriz A (numpy array)
    Salida: L si es posible, None si no es posible
    """
    A = np.array(A, dtype=float)
    n = A.shape[0]

    
    L = np.zeros((n, n))
    
    for i in range(n):
        for j in range(i + 1):
            if i == j:
                sum_val = 0.0
                for k in range(j):
                    sum_val += L[j, k]**2
                
                value = A[j, j] - sum_val
                
                if value <= 1e-10:
                    print("La factorización no es posible: la matriz no es definida positiva")
                    return None
                
                L[j, j] = np.sqrt(value)
            else:
                sum_val = 0.0
                for k in range(j):
                    sum_val += L[i, k] * L[j, k]
                
                L[i, j] = (A[i, j] - sum_val) / L[j, j]
    
    return L

In [10]:
print("\nEjemplo LDLt:")
A1 = np.array([
    [10, 2, 1],
    [2, 1, -2],
    [1, -2, 10]
])

print("Matriz A:")
print(A1)

L, D = ldlt_factorization(A1)
print("\nMatriz L:")
print(L)
print("\nMatriz D:")
print(D)


Ejemplo LDLt:
Matriz A:
[[10  2  1]
 [ 2  1 -2]
 [ 1 -2 10]]

Matriz L:
[[ 1.          0.          0.        ]
 [ 0.2         1.          0.        ]
 [ 0.1        -3.66666667  1.        ]]

Matriz D:
[[10.          0.          0.        ]
 [ 0.          0.6         0.        ]
 [ 0.          0.          1.83333333]]


In [11]:
print("\nEjemplo Cholesky:")
A3 = np.array([
    [10, 2, 1],
    [2, 1, -2],
    [1, -2, 10]
])

print("Matriz A:")
print(A3)

L = cholesky_factorization(A3)
print("\nMatriz L:")
print(L)


Ejemplo Cholesky:
Matriz A:
[[10  2  1]
 [ 2  1 -2]
 [ 1 -2 10]]

Matriz L:
[[ 3.16227766  0.          0.        ]
 [ 0.63245553  0.77459667  0.        ]
 [ 0.31622777 -2.84018779  1.3540064 ]]
