In [1]:
import numpy as np
from numpy import linalg as LA

In [ ]:

def potencia_inversa(A, mu=0, tol=1e-7, max_iter=1000):
    n = A.shape[0]
    
    # Vector inicial aleatorio
    v = np.random.rand(n)
    v = v / np.linalg.norm(v)
    
    # Matriz desplazada: (A - mu*I)
    A_shifted = A - mu * np.eye(n)
    
    eigenvalue_old = 0
    
    for iteration in range(max_iter):
        # Resolver el sistema (A - mu*I) * v_new = v_old
        try:
            v_new = np.linalg.solve(A_shifted, v)
        except np.linalg.LinAlgError:
            # Si la matriz es singular, mu es un eigenvalor exacto
            return mu, v, iteration
        
        # Normalizar
        v_new = v_new / np.linalg.norm(v_new)
        
        # Calcular el eigenvalor
        eigenvalue = np.dot(v_new, np.dot(A, v_new)) / np.dot(v_new, v_new)
        
        # Verificar convergencia
        if abs(eigenvalue - eigenvalue_old) < tol:
            return eigenvalue, v_new, iteration + 1
        
        eigenvalue_old = eigenvalue
        v = v_new
    
    return eigenvalue, v, max_iter

In [3]:
A = np.array([[17, 1, 2], [1, 14, -2], [2, -2, 20]], dtype=float)
    
eval1, evec1, _ = potencia_inversa(A, mu=0, tol=1e-7)
eval2, evec2, _ = potencia_inversa(A, mu=np.trace(A)/3, tol=1e-7)
eval3, evec3, _ = potencia_inversa(A, mu=np.trace(A)-eval1-eval2, tol=1e-7)

eigenvalues_impl = np.array([eval1, eval2, eval3])
eigenvectors_impl = np.array([evec1, evec2, evec3]).T

eigenvalues_numpy, eigenvectors_numpy = LA.eig(A)

In [ ]:
#Con potencia inversa
eigenvalues_impl

array([12.78541486, 16.94443491, 21.27015032])

In [5]:
#Con numpy
eigenvalues_numpy

array([21.27015032, 16.94443491, 12.78541476])

In [7]:
#Diferencia
np.abs(np.sort(eigenvalues_impl) - np.sort(eigenvalues_numpy))

array([1.00518120e-07, 1.77635684e-14, 3.55271368e-15])