In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
def descomposicion_svd(A):
    m, n = A.shape
    AtA = A.T @ A
    eigenvalues, V = LA.eig(AtA)
    
    singular_values = np.sqrt(np.abs(eigenvalues))
    idx = np.argsort(singular_values)[::-1]
    singular_values = singular_values[idx]
    V = V[:, idx]
    
    U = A @ V
    for i in range(min(m, n)):
        if singular_values[i] > 1e-10:
            U[:, i] = U[:, i] / singular_values[i]
    
    return U[:, :min(m, n)], singular_values[:min(m, n)], V.T

In [3]:
A = np.random.rand(8, 5)
    
U, s, Vt = descomposicion_svd(A)
U_numpy, s_numpy, Vt_numpy = LA.svd(A, full_matrices=False)

In [4]:
U_numpy, s_numpy, Vt_numpy

(array([[-0.28324378,  0.12326906,  0.17960827,  0.52353558, -0.16237455],
        [-0.29740132, -0.23678589, -0.14539317,  0.01869188,  0.65021991],
        [-0.46808274,  0.50532313, -0.30179937,  0.41634338,  0.11367073],
        [-0.51682251, -0.07366422,  0.69885331, -0.22503464, -0.19405225],
        [-0.35583641,  0.0753631 , -0.54848786, -0.46603382, -0.50015151],
        [-0.2259717 ,  0.40114512,  0.1377534 , -0.4998779 ,  0.41091966],
        [-0.27716292, -0.59520232, -0.21722784, -0.03156287,  0.18279365],
        [-0.3010256 , -0.38353159, -0.01095509,  0.18307662, -0.21874927]]),
 array([2.91269364, 0.87187628, 0.73989375, 0.66086336, 0.61416406]),
 array([[-0.29637244, -0.50295368, -0.35483719, -0.38547261, -0.62024383],
        [ 0.60529084, -0.28890546, -0.646396  ,  0.35061553,  0.09694124],
        [-0.48469173,  0.58494867, -0.63405085,  0.14083173,  0.03247954],
        [ 0.29463872,  0.19418663, -0.21518168, -0.84153206,  0.34785085],
        [ 0.47333743,  0.532