In [2]:
import numpy as np
from numpy import linalg as LA

In [1]:
def metodo_qr(A, tol=1e-7, max_iter=1000):
    n = A.shape[0]
    Ak = A.copy()
    Q_total = np.eye(n)
    
    for _ in range(max_iter):
        Q, R = np.linalg.qr(Ak)
        Ak_new = R @ Q
        Q_total = Q_total @ Q
        
        if np.linalg.norm(Ak_new - Ak) < tol:
            break
        Ak = Ak_new
    
    eigenvalues = np.diag(Ak)
    eigenvectors = Q_total
    
    return eigenvalues, eigenvectors


In [3]:
A = np.array([[8, 3, 1, 7], [3, 3, 5, 4], [1, 5, 4, -2], [7, 4, -2, 2]], dtype=float)

eigenvalues_qr, eigenvectors_qr = metodo_qr(A, tol=1e-7)
eigenvalues_numpy, eigenvectors_numpy = LA.eig(A)

In [ ]:
#metodo QR
eigenvalues_qr
   

array([14.83555948,  7.34315248, -5.19461582,  0.01590386])

In [5]:
#con numpy
eigenvalues_numpy

array([14.83555948, -5.19461582,  0.01590386,  7.34315248])

In [6]:
np.abs(np.sort(eigenvalues_qr) - np.sort(eigenvalues_numpy))

array([7.99360578e-15, 1.79023463e-15, 1.77635684e-15, 2.30926389e-14])